// Code generated by MockGen. DO NOT EDIT.
// Source: selector.go
//
// Generated by this command:
//
//	mockgen -source=selector.go -destination=mocks/mock_selector.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIntPrng is a mock of IntPrng interface.
type MockIntPrng struct {
	ctrl     *gomock.Controller
	recorder *MockIntPrngMockRecorder
	isgomock struct{}
}

// MockIntPrngMockRecorder is the mock recorder for MockIntPrng.
type MockIntPrngMockRecorder struct {
	mock *MockIntPrng
}

// NewMockIntPrng creates a new mock instance.
func NewMockIntPrng(ctrl *gomock.Controller) *MockIntPrng {
	mock := &MockIntPrng{ctrl: ctrl}
	mock.recorder = &MockIntPrngMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIntPrng) EXPECT() *MockIntPrngMockRecorder {
	return m.recorder
}

// IntN mocks base method.
func (m *MockIntPrng) IntN(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntN", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntN indicates an expected call of IntN.
func (mr *MockIntPrngMockRecorder) IntN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntN", reflect.TypeOf((*MockIntPrng)(nil).IntN), n)
}
