// Code generated by MockGen. DO NOT EDIT.
// Source: dict.go
//
// Generated by this command:
//
//	mockgen -source=dict.go -destination=mocks/mock_dict.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	ctg "hangman/internal/domain/ctg"
	dict "hangman/internal/domain/dict"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Category mocks base method.
func (m *MockRepository) Category(arg0 ctg.Category) (dict.Category, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Category", arg0)
	ret0, _ := ret[0].(dict.Category)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Category indicates an expected call of Category.
func (mr *MockRepositoryMockRecorder) Category(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Category", reflect.TypeOf((*MockRepository)(nil).Category), arg0)
}

// ListCategories mocks base method.
func (m *MockRepository) ListCategories() []dict.Category {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCategories")
	ret0, _ := ret[0].([]dict.Category)
	return ret0
}

// ListCategories indicates an expected call of ListCategories.
func (mr *MockRepositoryMockRecorder) ListCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCategories", reflect.TypeOf((*MockRepository)(nil).ListCategories))
}
