// Code generated by MockGen. DO NOT EDIT.
// Source: ui.go
//
// Generated by this command:
//
//	mockgen -source=ui.go -destination=../app/mode/mocks/mock_ui.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	session "hangman/internal/domain/session"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserInterface is a mock of UserInterface interface.
type MockUserInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserInterfaceMockRecorder
	isgomock struct{}
}

// MockUserInterfaceMockRecorder is the mock recorder for MockUserInterface.
type MockUserInterfaceMockRecorder struct {
	mock *MockUserInterface
}

// NewMockUserInterface creates a new mock instance.
func NewMockUserInterface(ctrl *gomock.Controller) *MockUserInterface {
	mock := &MockUserInterface{ctrl: ctrl}
	mock.recorder = &MockUserInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserInterface) EXPECT() *MockUserInterfaceMockRecorder {
	return m.recorder
}

// AskRune mocks base method.
func (m *MockUserInterface) AskRune() rune {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AskRune")
	ret0, _ := ret[0].(rune)
	return ret0
}

// AskRune indicates an expected call of AskRune.
func (mr *MockUserInterfaceMockRecorder) AskRune() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AskRune", reflect.TypeOf((*MockUserInterface)(nil).AskRune))
}

// Clear mocks base method.
func (m *MockUserInterface) Clear() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Clear")
}

// Clear indicates an expected call of Clear.
func (mr *MockUserInterfaceMockRecorder) Clear() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clear", reflect.TypeOf((*MockUserInterface)(nil).Clear))
}

// PrintGameStatus mocks base method.
func (m *MockUserInterface) PrintGameStatus(status session.Status) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintGameStatus", status)
}

// PrintGameStatus indicates an expected call of PrintGameStatus.
func (mr *MockUserInterfaceMockRecorder) PrintGameStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintGameStatus", reflect.TypeOf((*MockUserInterface)(nil).PrintGameStatus), status)
}

// PrintGuessResult mocks base method.
func (m *MockUserInterface) PrintGuessResult(result session.GuessResult, leftAtt int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintGuessResult", result, leftAtt)
}

// PrintGuessResult indicates an expected call of PrintGuessResult.
func (mr *MockUserInterfaceMockRecorder) PrintGuessResult(result, leftAtt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintGuessResult", reflect.TypeOf((*MockUserInterface)(nil).PrintGuessResult), result, leftAtt)
}

// PrintHangman mocks base method.
func (m *MockUserInterface) PrintHangman(leftAttempts int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintHangman", leftAttempts)
}

// PrintHangman indicates an expected call of PrintHangman.
func (mr *MockUserInterfaceMockRecorder) PrintHangman(leftAttempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintHangman", reflect.TypeOf((*MockUserInterface)(nil).PrintHangman), leftAttempts)
}

// PrintHint mocks base method.
func (m *MockUserInterface) PrintHint(hint string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintHint", hint)
}

// PrintHint indicates an expected call of PrintHint.
func (mr *MockUserInterfaceMockRecorder) PrintHint(hint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintHint", reflect.TypeOf((*MockUserInterface)(nil).PrintHint), hint)
}

// Println mocks base method.
func (m *MockUserInterface) Println(a ...any) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	m.ctrl.Call(m, "Println", varargs...)
}

// Println indicates an expected call of Println.
func (mr *MockUserInterfaceMockRecorder) Println(a ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Println", reflect.TypeOf((*MockUserInterface)(nil).Println), a...)
}
